# Generated by Django 5.2.17 on 2026-09-04 14:18

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Upload an image with a .jpg, .jpeg, .png, or .webp extension.'), core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(upload_to='activities/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Upload an image with a .jpg, .jpeg, .png, or .webp extension.'), core.validators.validate_image_file_size]),
        ),
    ]
