# Generated by Django 5.2.17 on 2026-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
