"""
Django settings for config project.

Generated by 'django-admin startproject'.

Alliance Yuwa Club
Production configuration supporting:
- Django REST Framework
- PostgreSQL / Supabase
- WhiteNoise
- Optional Supabase S3-compatible media storage
"""

import os
import secrets
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.core.files.storage import FileSystemStorage


# =============================================================================
# PATHS
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT HELPERS
# =============================================================================

def get_list_setting(name, default="", environment=None):
    """
    Read a comma-separated environment variable as a list.

    Example:
        ALLOWED_HOSTS=localhost,127.0.0.1

    becomes:

        ["localhost", "127.0.0.1"]
    """
    environment = os.environ if environment is None else environment

    raw_value = environment.get(name, default)

    if not raw_value:
        return []

    return [
        value.strip()
        for value in raw_value.split(",")
        if value.strip()
    ]


def get_boolean_setting(name, default=False, environment=None):
    """Read a boolean environment variable."""
    environment = os.environ if environment is None else environment

    value = environment.get(name)

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def get_required_environment(name):
    """
    Return a required environment variable.

    Raises a clear configuration error when missing.
    """
    value = os.environ.get(name)

    if not value:
        raise ImproperlyConfigured(
            f"Required environment variable '{name}' is missing."
        )

    return value


# =============================================================================
# SECURITY
# =============================================================================

DEBUG = get_boolean_setting("DEBUG", default=True)

SECRET_KEY = os.environ.get("SECRET_KEY")

if not SECRET_KEY:
    if DEBUG:
        # Development-only generated key.
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set when DEBUG=False."
        )


ALLOWED_HOSTS = get_list_setting(
    "ALLOWED_HOSTS",
    default=(
        "localhost,127.0.0.1,"
        "allianceyuwaclub.org.np,"
        "api.allianceyuwaclub.org.np,"
        "www.allianceyuwaclub.org.np"
    ),
)


# =============================================================================
# PUBLIC SITE
# =============================================================================

# Public frontend origin (Vercel) used to build canonical URLs for the sitemap.
# The frontend and Django API are deployed as separate services, so sitemap
# URLs point at the public site host rather than this service's own host.
# Mirrors the frontend VITE_SITE_URL value.
FRONTEND_BASE_URL = os.environ.get(
    "FRONTEND_BASE_URL", "https://allianceyuwaclub.org.np"
).rstrip("/")


# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    # Third-party
    "corsheaders",
    "rest_framework",

    # Local apps
    "core",
    "activities",
    "events",
    "news",
    "team",
    "memberships",
    "gallery",
    "contact",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# =============================================================================
# DATABASE
# =============================================================================

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Preferred production configuration.
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
elif os.environ.get("POSTGRES_DB"):
    # Local / Docker / fallback PostgreSQL configuration.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "OPTIONS": {
                "sslmode": os.environ.get("POSTGRES_SSLMODE", "require"),
            },
        }
    }
else:
    # Local development fallback.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "contact_submission": os.environ.get(
            "CONTACT_SUBMISSION_THROTTLE_RATE",
            "5/hour",
        ),
        "membership_application": os.environ.get(
            "MEMBERSHIP_APPLICATION_THROTTLE_RATE",
            "3/day",
        ),
    },
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),
    "PAGE_SIZE": int(os.environ.get("API_PAGE_SIZE", "12")),
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "MAX_PAGE_SIZE": 100,
}


# =============================================================================
# CORS / CSRF
# =============================================================================

CORS_ALLOWED_ORIGINS = get_list_setting(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:5173,"
        "http://127.0.0.1:5173"
    ),
)

CSRF_TRUSTED_ORIGINS = get_list_setting(
    "CSRF_TRUSTED_ORIGINS",
)


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# MEDIA STORAGE
# =============================================================================

MEDIA_ROOT = BASE_DIR / "media"


def get_media_storage_configuration(environment=None):
    """
    Configure default media storage and static-file storage.

    Local/default:
        FileSystemStorage

    Optional production:
        Supabase S3-compatible storage
    """
    environment = os.environ if environment is None else environment

    staticfiles_storage = {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    }

    use_supabase_storage = get_boolean_setting(
        "USE_SUPABASE_STORAGE",
        default=False,
        environment=environment,
    )

    if not use_supabase_storage:
        return {
            "media_url": "/media/",
            "storages": {
                "default": {
                    "BACKEND": (
                        "django.core.files.storage."
                        "FileSystemStorage"
                    ),
                },
                "staticfiles": staticfiles_storage,
            },
        }

    required_settings = (
        "SUPABASE_STORAGE_BUCKET",
        "SUPABASE_S3_ACCESS_KEY_ID",
        "SUPABASE_S3_SECRET_ACCESS_KEY",
        "SUPABASE_S3_ENDPOINT_URL",
    )

    missing_settings = [
        setting
        for setting in required_settings
        if not environment.get(setting)
    ]

    if missing_settings:
        raise ImproperlyConfigured(
            "Missing Supabase Storage environment variables: "
            + ", ".join(missing_settings)
        )

    bucket_name = environment["SUPABASE_STORAGE_BUCKET"]

    endpoint_url = environment[
        "SUPABASE_S3_ENDPOINT_URL"
    ].rstrip("/")

    public_media_url = environment.get(
        "SUPABASE_STORAGE_PUBLIC_URL",
        "",
    ).rstrip("/")

    if not public_media_url:
        public_endpoint = endpoint_url.removesuffix("/s3")

        public_media_url = (
            f"{public_endpoint}/object/public/{bucket_name}"
        )

    if public_media_url.startswith("https://"):
        url_protocol = "https:"
        custom_domain = public_media_url.removeprefix(
            "https://"
        )
    elif public_media_url.startswith("http://"):
        url_protocol = "http:"
        custom_domain = public_media_url.removeprefix(
            "http://"
        )
    else:
        raise ImproperlyConfigured(
            "SUPABASE_STORAGE_PUBLIC_URL must start with "
            "http:// or https://."
        )

    return {
        "media_url": f"{public_media_url}/",
        "storages": {
            "default": {
                "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
                "OPTIONS": {
                    "access_key": environment[
                        "SUPABASE_S3_ACCESS_KEY_ID"
                    ],
                    "secret_key": environment[
                        "SUPABASE_S3_SECRET_ACCESS_KEY"
                    ],
                    "bucket_name": bucket_name,
                    "endpoint_url": endpoint_url,
                    "region_name": environment.get(
                        "SUPABASE_S3_REGION",
                        "us-east-1",
                    ),
                    "addressing_style": "path",
                    "querystring_auth": False,
                    "custom_domain": custom_domain,
                    "url_protocol": url_protocol,
                },
            },
            "staticfiles": staticfiles_storage,
        },
    }


_media_storage_configuration = (
    get_media_storage_configuration()
)

MEDIA_URL = _media_storage_configuration["media_url"]

STORAGES = _media_storage_configuration["storages"]


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# SECURITY HEADERS
# =============================================================================

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


if not DEBUG:
    SECURE_SSL_REDIRECT = get_boolean_setting(
        "SECURE_SSL_REDIRECT",
        default=True,
    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = int(
        os.environ.get(
            "SECURE_HSTS_SECONDS",
            "31536000",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = get_boolean_setting(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS",
        default=False,
    )

    SECURE_HSTS_PRELOAD = get_boolean_setting(
        "SECURE_HSTS_PRELOAD",
        default=False,
    )

    SECURE_REFERRER_POLICY = os.environ.get(
        "SECURE_REFERRER_POLICY",
        "same-origin",
    )

    # Optional CSP can be added later after verifying all frontend
    # and media sources used in production.
else:
    SECURE_SSL_REDIRECT = get_boolean_setting(
        "SECURE_SSL_REDIRECT",
        default=False,
    )

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False


# =============================================================================
# EMAIL
# =============================================================================

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "webmaster@localhost",
)